// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADNwVOtppDe33drrkiOF73Kfxav9zqQTI',
    appId: '1:185304471481:web:4164aad9a50edb2b0ac868',
    messagingSenderId: '185304471481',
    projectId: 'test-project-els-id',
    authDomain: 'test-project-els-id.firebaseapp.com',
    storageBucket: 'test-project-els-id.firebasestorage.app',
    measurementId: 'G-60G33L6GGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBP4MKh4ODT89yhjkrWfMjO_-d0X75WoE',
    appId: '1:185304471481:android:4a1df5367ab0f9180ac868',
    messagingSenderId: '185304471481',
    projectId: 'test-project-els-id',
    storageBucket: 'test-project-els-id.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoGK65SH62q1Nj_StTFO6kymyqgMsl1zE',
    appId: '1:185304471481:ios:c3d7d9e32ffedb750ac868',
    messagingSenderId: '185304471481',
    projectId: 'test-project-els-id',
    storageBucket: 'test-project-els-id.firebasestorage.app',
    iosBundleId: 'com.example.projectAplikasiAbsensiHrdEls',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoGK65SH62q1Nj_StTFO6kymyqgMsl1zE',
    appId: '1:185304471481:ios:c3d7d9e32ffedb750ac868',
    messagingSenderId: '185304471481',
    projectId: 'test-project-els-id',
    storageBucket: 'test-project-els-id.firebasestorage.app',
    iosBundleId: 'com.example.projectAplikasiAbsensiHrdEls',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADNwVOtppDe33drrkiOF73Kfxav9zqQTI',
    appId: '1:185304471481:web:a3c1259f19eace670ac868',
    messagingSenderId: '185304471481',
    projectId: 'test-project-els-id',
    authDomain: 'test-project-els-id.firebaseapp.com',
    storageBucket: 'test-project-els-id.firebasestorage.app',
    measurementId: 'G-2B07Z2MQC0',
  );

}